update=Di 18 Mär 2014 19:54:54 CET
last_client=pcbnew
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=KeithleyUpgrade.net
UseCmpFile=1
PadDrill=0
PadDrillOvalY=0
PadSizeH=0.19558
PadSizeV=1.4986
PcbTextSizeV=1
PcbTextSizeH=1
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[pcbnew/libraries]
LibDir=
