name: Simply Grey
markdown: redcarpet
pygments: true
github: https://github.com/asanza
about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
urls:
    - text: github
      url: https://github.com/asanza
    - text: email
      url: mailto:exaem@exaem.co.uk
baseurl: '/keithley_199'
