site_name: '42'

theme: 'readthedocs'
copyright: 'Copyright © 2016 Diego F. Asanza'

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

pages:
- Home: 'index.md'
