# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :test_file_prefix: test_
  :release_build: TRUE

:environment:
  - :mcu:  32MX350F256L
  - :freq: 80000000UL
  - :uart: UART1
  - :path:
    - /bin
    - /usr/bin
    - /opt/microchip/xc32/v1.31/bin
    - /opt/microchip/mplabx/v3.26/mplab_ide/bin

:extension:
  :executable: .elf
  :assembly: .S

:release_build:
  :output: k199
  :use_assembly: TRUE

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - +:src/**
    - -:src/scpi-parser/examples/**
    - -:src/scpi-parser/libscpi/test/**
  :support:
    - test/support
  :include:

:defines:
  :commmon: &common_defines
    - UNITY_INCLUDE_DOUBLE
    - UNITY_DOUBLE_PRECISION=1e-6
  :release:
    - REPOVERSION=1
    - REPOBRANCH=1
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :test_compiler:
    :executable: xc32-gcc
    :arguments:
      - -mprocessor=#{ENV['MCU']}
      - -x c
      - -c
      - -g
      - -MMD
      - -Wno-packed-bitfield-compat
      - -Wno-pragmas
      - -lm
      - -fno-short-double
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wall

  :test_linker:
    :executable: xc32-gcc
    :arguments:
      - ${1}
      - -mprocessor=#{ENV['MCU']}
      - -lm
      - --gc-sections
      - -fno-short-double
      - -o "./build/test/TestBuild.elf"
      - -Wl,-Tp#{ENV['MCU']}.ld,--defsym=_min_heap_size=2000,-Map=./build/test/TestOutput.map,--report-mem
      - --defsym=_min_heap_size=32440
      - --defsym=_min_stack_size=1056
  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :unix # win inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb

  :release_assembler:
    :executable: xc32-gcc
    :arguments:
      - -mprocessor=#{ENV['MCU']}
      - -c
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - "${1}"
      - -o "${2}"      
      - -Wa,--defsym=__MPLAB_BUILD=1,--gdwarf-2 

  :release_compiler:
    :executable: xc32-gcc
    :arguments:
      - -mprocessor=#{ENV['MCU']}
      - -x c
      - -c
      - -g
      - -MMD
      - -Wno-packed-bitfield-compat
      - -Wno-pragmas
      - -lm
      - -fno-short-double
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - -Wall
  :release_linker:
    :executable: xc32-gcc
    :arguments:
      - ${1}
      - -mprocessor=#{ENV['MCU']}
      - -lm
      - --gc-sections
      - -fno-short-double
      - -o "./build/test/TestBuild.elf"
      - -Wl,-Tp#{ENV['MCU']}.ld,--defsym=_min_heap_size=2000,-Map=./build/release/app.map,--report-mem
      - --defsym=_min_heap_size=32440
      - --defsym=_min_stack_size=1056

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
