# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: FALSE
  :test_file_prefix: test_
 
#:release_build:
# :output: MyPicApp.out
# :use_assembly: FALSE

:environment:

:extension:
  :executable: .elf

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :include:
#    - /opt/microchip/xc32/v1.31/pic32-libs/include/peripheral/

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines
#    - CMOCK_MEM_INDEX_TYPE=uint16_t
#    - CMOCK_MEM_PTR_AS_INT=uint16_t
#    - CMOCK_MEM_ALIGN=1
 
#   - CMOCK_MEM_DYNAMIC
#   - CMOCK_MEM_SIZE=512
 
#    - CMOCK_MEM_STATIC
#    - CMOCK_MEM_SIZE=1024
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :test_compiler:
    :executable: xc32-gcc
    :arguments:
      - -mprocessor=32MX350F256L
      - -x c
      - -c
      - -g
      - -mips16
      - -MMD
      - -Wno-packed-bitfield-compat
      - -minterlink-compressed
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wall
      #- -pedantic
      #- -Werror  # We can't keep this on during test becuase of a CMock pointer issue
     # - -Os

  :test_linker:
    :executable: xc32-gcc
    :arguments:
      - -mprocessor=32MX350F256L
      - -mips16
      - -minterlink-compressed
      - --gc-sections
      - ${1}
      - -o "./build/test/TestBuild.elf"
      #- -L
      - -Wl,-Tp32MX350F256L.ld,-Map=./build/test/TestOutput.map,--report-mem
      - --defsym=_min_heap_size=32440
      - --defsym=_min_stack_size=1056
  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :unix # win inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb

  :release_compiler:
    :executable: xc32-gcc
    :arguments:
      - -mcpu=32MX150F128D
      - -x c
      - -minterlink-compressed
      - -c
      - "${1}"
      - -o "${2}"
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      - -Werror
      - -Os
      - -mlarge-code
      - -mlarge-arrays
  :release_linker:
    :executable: xc32-gcc
    :arguments:
      - -mcpu=32MX150F128D
      - ${1}
      - ${1}
      - -o "${2}"
      - -Wl,-Tp32MX150F128D.gld,-Map=./build/release/MyPicApp.map,--report-mem

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...